# Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
cd /content/drive/My Drive/Study/Udemy_Machine-Learning-A-Z/Classification

/content/drive/My Drive/Study/Udemy_Machine-Learning-A-Z/Classification


# Import the dataset

In [4]:
dataset_df = pd.read_csv('breast-cancer-wisconsin-data.csv', na_values = '?')   # The symbol '?' is assumed as missing values or NaN.

dataset_df

# Sample code number  Clump Thickness  Uniformity of Cell Size  \
0                 1000025                5                        1   
1                 1002945                5                        4   
2                 1015425                3                        1   
3                 1016277                6                        8   
4                 1017023                4                        1   
..                    ...              ...                      ...   
694                776715                3                        1   
695                841769                2                        1   
696                888820                5                       10   
697                897471                4                        8   
698                897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
694                         1                  1                            3   
695                         1                  1                            2   
696                        10                  3                            7   
697                         6                  4                            3   
698                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1.0                3                1        1      2  
1           10.0                3                2        1      2  
2            2.0                3                1        1      2  
3            4.0                3                7        1      2  
4            1.0                3                1        1      2  
..           ...              ...              ...      ...    ...  
694          2.0                1                1        1      2  
695          1.0                1                1        1      2  
696          3.0                8               10        2      4  
697          4.0               10                6        1      4  
698          5.0               10                4        1      4  

[699 rows x 11 columns]

# Data pre-processing

In [5]:
dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   # Sample code number         699 non-null    int64  
 1   Clump Thickness              699 non-null    int64  
 2   Uniformity of Cell Size      699 non-null    int64  
 3   Uniformity of Cell Shape     699 non-null    int64  
 4   Marginal Adhesion            699 non-null    int64  
 5   Single Epithelial Cell Size  699 non-null    int64  
 6   Bare Nuclei                  683 non-null    float64
 7   Bland Chromatin              699 non-null    int64  
 8   Normal Nucleoli              699 non-null    int64  
 9   Mitoses                      699 non-null    int64  
 10  Class                        699 non-null    int64  
dtypes: float64(1), int64(10)
memory usage: 60.2 KB


In [7]:
# Checking the missing values.

dataset_df.isnull().sum()

# The column 'Bare Nuclei' has 16 missing values or nan values which are '?' symbol.

# Sample code number            0
Clump Thickness                 0
Uniformity of Cell Size         0
Uniformity of Cell Shape        0
Marginal Adhesion               0
Single Epithelial Cell Size     0
Bare Nuclei                    16
Bland Chromatin                 0
Normal Nucleoli                 0
Mitoses                         0
Class                           0
dtype: int64

In [8]:
# Drop the rows which has at least one missing value.

dataset_df.dropna(inplace = True)

dataset_df

# Sample code number  Clump Thickness  Uniformity of Cell Size  \
0                 1000025                5                        1   
1                 1002945                5                        4   
2                 1015425                3                        1   
3                 1016277                6                        8   
4                 1017023                4                        1   
..                    ...              ...                      ...   
694                776715                3                        1   
695                841769                2                        1   
696                888820                5                       10   
697                897471                4                        8   
698                897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
694                         1                  1                            3   
695                         1                  1                            2   
696                        10                  3                            7   
697                         6                  4                            3   
698                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1.0                3                1        1      2  
1           10.0                3                2        1      2  
2            2.0                3                1        1      2  
3            4.0                3                7        1      2  
4            1.0                3                1        1      2  
..           ...              ...              ...      ...    ...  
694          2.0                1                1        1      2  
695          1.0                1                1        1      2  
696          3.0                8               10        2      4  
697          4.0               10                6        1      4  
698          5.0               10                4        1      4  

[683 rows x 11 columns]

In [9]:
dataset_df.isnull().sum()

# Now no missing values in any column.

# Sample code number           0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [10]:
dataset_df.describe()

# Sample code number  Clump Thickness  Uniformity of Cell Size  \
count          6.830000e+02       683.000000               683.000000   
mean           1.076720e+06         4.442167                 3.150805   
std            6.206440e+05         2.820761                 3.065145   
min            6.337500e+04         1.000000                 1.000000   
25%            8.776170e+05         2.000000                 1.000000   
50%            1.171795e+06         4.000000                 1.000000   
75%            1.238705e+06         6.000000                 5.000000   
max            1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                683.000000         683.000000   
mean                   3.215227           2.830161   
std                    2.988581           2.864562   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   683.000000   683.000000       683.000000   
mean                      3.234261     3.544656         3.445095   
std                       2.223085     3.643857         2.449697   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     6.000000         5.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses       Class  
count       683.000000  683.000000  683.000000  
mean          2.869693    1.603221    2.699854  
std           3.052666    1.732674    0.954592  
min           1.000000    1.000000    2.000000  
25%           1.000000    1.000000    2.000000  
50%           1.000000    1.000000    2.000000  
75%           4.000000    1.000000    4.000000  
max          10.000000   10.000000    4.000000

In [11]:
X = dataset_df.iloc[:, :-1].values   # Matrix of features.
y = dataset_df.iloc[:, -1].values   # Dependent variable or target variable vector.

In [12]:
X

array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 3.000000e+00,
        2.000000e+00, 1.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 8.000000e+00,
        1.000000e+01, 2.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 1.000000e+01,
        6.000000e+00, 1.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 1.000000e+01,
        4.000000e+00, 1.000000e+00]])

In [13]:
X.shape

(683, 10)

In [33]:
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 2,
       4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2,
       2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 2,
       4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 2,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4,

In [16]:
y.shape

(683,)

# Splitting into train and test sets

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(546, 10)
(137, 10)
(546,)
(137,)


# Feature scaling

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
X_train

array([[-0.49838781,  1.98839518, -0.69781134, ...,  0.61907387,
         0.34532102, -0.33863738],
       [ 0.19242611, -1.22468404, -0.69781134, ..., -0.18860673,
        -0.62157783, -0.33863738],
       [-1.00461394,  0.20335117, -0.69781134, ..., -0.18860673,
        -0.62157783, -0.33863738],
       ...,
       [ 0.1853572 , -1.22468404, -0.69781134, ..., -0.99628733,
        -0.62157783, -0.33863738],
       [ 0.3178948 , -0.51066644, -0.69781134, ..., -0.59244703,
        -0.62157783, -0.33863738],
       [-1.05380275,  1.98839518,  1.90512627, ...,  1.42675446,
         1.31221987, -0.33863738]])

In [17]:
X_test

array([[ 0.12494975, -1.22468404, -0.69781134, ..., -0.99628733,
        -0.62157783, -0.33863738],
       [ 0.09925676, -0.51066644, -0.69781134, ..., -0.59244703,
        -0.62157783, -0.33863738],
       [-0.56729485,  0.20335117,  0.60365746, ...,  0.21523357,
         0.0230214 , -0.33863738],
       ...,
       [-1.06671597, -0.15365763, -0.69781134, ..., -0.99628733,
        -0.62157783, -0.33863738],
       [ 0.33247739, -0.15365763,  2.23049348, ...,  2.23443506,
         2.27911872, -0.33863738],
       [ 0.06979061, -0.86767524, -0.69781134, ..., -0.59244703,
        -0.62157783, -0.33863738]])

# Training the logistic regression model on the training set

In [18]:
from sklearn.linear_model import LogisticRegression

classifier_log_reg = LogisticRegression(random_state = 0)

classifier_log_reg.fit(X_train, y_train)

LogisticRegression(random_state=0)

# Prediction on the training set

In [19]:
y_pred_train = classifier_log_reg.predict(X_train)
y_pred_train

array([4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 4, 2,
       4, 4, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 4,
       4, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2,
       2, 4, 4, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2,
       2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2,
       2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 4, 4, 4, 2,
       2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4,
       4, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 2,

In [20]:
for a, b in zip(y_pred_train, y_train):
    print(a, b)

4 4
2 2
2 2
2 2
4 4
2 2
2 2
2 2
4 2
4 4
2 2
4 4
2 2
4 4
2 4
2 2
2 2
2 2
2 2
4 4
4 4
2 2
4 4
4 4
4 4
4 4
2 4
4 4
2 2
2 2
2 2
2 2
2 2
2 2
4 4
4 4
4 4
2 2
2 2
2 2
4 4
2 2
2 2
4 4
4 4
2 2
4 4
2 2
2 2
4 4
4 4
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
4 4
2 2
2 2
2 2
2 2
2 2
4 4
4 4
2 2
4 4
2 2
4 2
4 2
4 4
2 2
2 2
2 2
2 2
4 4
4 4
2 2
2 2
4 4
4 4
2 2
2 2
4 4
4 4
2 2
4 4
2 2
4 4
4 4
2 2
2 2
2 2
4 4
2 2
4 4
2 2
4 4
2 2
2 2
2 2
2 2
2 2
4 4
2 2
2 2
4 4
2 2
2 2
4 4
2 2
2 2
2 2
2 2
2 2
4 4
2 2
2 2
4 4
2 2
4 4
2 2
2 2
4 4
4 4
4 4
2 2
2 2
2 2
2 2
2 2
2 2
4 4
4 4
2 2
2 2
2 2
4 2
2 2
2 2
2 2
4 4
2 2
2 2
4 4
2 2
2 2
2 2
2 2
2 2
2 2
2 2
4 4
2 2
2 2
2 2
4 4
4 4
2 2
4 4
2 2
2 2
2 2
4 4
2 2
2 2
2 2
4 4
4 4
2 2
4 4
2 2
2 2
4 4
2 2
2 2
2 2
2 2
2 2
2 2
2 2
4 4
4 4
4 4
4 4
2 2
4 4
2 2
4 4
2 2
4 4
4 4
4 4
2 2
2 2
4 4
2 2
2 2
2 2
2 2
4 4
4 4
2 2
2 2
2 2
4 4
2 2
2 2
4 4
2 2
2 2
2 2
2 2
4 4
2 4
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
4 4
2 2
4 4
2 2
2 2
2 2
2 2
2 2
2 2
4 4
4 4
4 4
4 4
2 2
2 2
4 4
2 2
4 4
2 2
4 4


In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score

print('The confusion matrix on the training set is: \n', confusion_matrix(y_train, y_pred_train))
print('The accuracy of the logistic regression model on the training set is =', accuracy_score(y_train, y_pred_train))

The confusion matrix on the training set is: 
 [[350   7]
 [  7 182]]
The accuracy of the logistic regression model on the training set is = 0.9743589743589743


# Prediction on the test set

In [28]:
y_pred_test = classifier_log_reg.predict(X_test)
y_pred_test

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2])

In [29]:
for a, b in zip(y_pred_test, y_test):
    print(a, b)

2 2
2 2
4 4
4 4
2 2
2 2
2 2
4 4
2 2
2 2
4 4
2 2
4 4
2 2
2 2
2 2
4 4
4 4
4 4
2 2
2 2
2 2
4 4
2 2
4 4
4 4
2 2
2 2
2 2
4 4
2 2
4 4
4 4
2 2
2 2
2 2
4 4
4 4
2 2
4 4
2 2
2 2
2 2
2 2
2 2
2 2
2 2
4 4
2 2
2 2
4 4
2 2
4 4
2 2
2 2
2 2
4 4
4 2
2 2
4 4
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
4 4
4 4
2 2
2 2
2 2
2 2
2 2
2 2
4 4
2 2
2 2
2 2
4 4
2 2
4 4
2 2
2 2
4 4
2 2
4 2
4 4
2 2
4 4
2 2
4 4
4 4
2 4
4 2
4 4
4 4
4 4
2 2
2 2
2 2
4 4
4 4
2 2
2 2
4 4
2 4
2 2
2 2
4 4
2 2
2 2
4 4
2 2
2 2
2 2
2 4
2 2
2 2
2 2
4 4
2 2
2 2
4 4
4 4
2 2
4 4
2 2
4 4
2 2
2 2
4 4
2 2
2 2
4 4
2 2


In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score

print('The confusion matrix on the test set is: \n', confusion_matrix(y_test, y_pred_test))
print('The accuracy of the logistic regression model on the test set is =', accuracy_score(y_test, y_pred_test))

The confusion matrix on the test set is: 
 [[84  3]
 [ 3 47]]
The accuracy of the logistic regression model on the test set is = 0.9562043795620438
